### ISSUE TITLE
Can't get the form to work

### ISSUE THREAD

**Issue by davidneedham** [mautic/mautic-drupal#16]
I installed the module, set our URL, and set the block to show on every page. I can confirm that the JS and tracking image being loaded by pulling up Chrome Inspector. No errors in the console. I cleared the cache and even disabled js aggregation to debug.

I tried putting the code in a block, and when that didn't work I tried it in a node. Both were using a text format that was showing full html (no filtering). The code is `{mauticform id=1 width=300px height=300px}` and I can confirm that our site has a form with the ID of 1.

Any ideas what else I should try?

**Comment by davidneedham** [comment]
Noticed someone asked about this over on the forum: [https://www.mautic.org/community/index.php//3237-how-to-embed-mautic-form-in-drupal-7/0](https://www.mautic.org/community/index.php//3237-how-to-embed-mautic-form-in-drupal-7/0).

**Comment by ronald070** [comment]
Hi,
I have exactly the same problem. maybe any news on this?

**Comment by davidneedham** [comment]
I wasn't able to fix the problem using the module, but if you follow the link in my last comment you can find my workaround using Webform and Zapier.

**Comment by ronald070** [comment]
Oke, Thank you.

**Comment by jordan8037310** [comment]
This is resolved with #23 merged to 7.x branch.
