### ISSUE TITLE
License for the code?

### ISSUE THREAD

**Issue by lightweight** [mautic/mautic-drupal#17]
Hello @dbhurley - just wondering if there's a license applied to this module? I'm assuming, given that it's Drupal-related, it'll use the GPL v2 or later, but it'd be great to see that clarified by the copyright holder :)

**Comment by dbhurley** [comment]
Fair. It is indeed the same as the rest of the project. Somehow it got left off this specific plugin. We will get it updated (unless you feel so lead to submit a PR to make it match the others) 🙂

**Comment by jordan8037310** [comment]
Merged with #18.
