### ISSUE TITLE
Branch organization

### ISSUE THREAD

**Issue by Ben-Coleman** [mautic/mautic-drupal#2]
I'd suggest that for this module, instead of having a master branch, and then having subdirectories for each main drupal version, each main drupal version should be a separate branch.  E.g., branch 6x should have the code for Drupal 6, and branch 7x should have the code for Drupal 7.  This is closer to how development is done in Drupal, allows users to pull the appropriate version of the module into a site via e.g. 'git clone -b 7x https://github.com/mautic/mautic-drupal.git .'.

**Comment by escopecz** [comment]
I agree. @dbhurley, could you create branches similar to https://github.com/drupal/drupal/branches? In our case, we need branches:
- 6.x
- 7.x

I suggest to rename master branch to 7.x and create branch 6.x.

**Comment by mbabker** [comment]
I think I might suggest master be for 8x since that's slowly working its way toward stable.

**Comment by escopecz** [comment]
No problem with that. I'll prepare version for 8.x as well.

**Comment by alanhartless** [comment]
Branches created.  @escopecz will be updating the files.
