### ISSUE TITLE
Do you have a mautic module for Drupal 8?

### ISSUE THREAD

**Issue by koobitor** [mautic/mautic-drupal#20]
I see on branch 8.x it is a drupal 7 version.
Hook
- menu
- help
- form
- block
  ref: https://www.drupal.org/update/modules/7/8

**Comment by escopecz** [comment]
There is a PR with D8. It'd be great if you'd be able to test it: https://github.com/mautic/mautic-drupal/pull/19

**Comment by RCheesley** [comment]
https://www.drupal.org/project/mautic you can find it here - closing this old issue :)
