### ISSUE TITLE
wrong mautic_base_url variable on trim function

### ISSUE THREAD

**Issue by koobitor** [mautic/mautic-drupal#21]
If you use "mautic.net" or domain is ".net" trim function with $character_mask arg "\t" will remove "t" character  form your mautic_base_url
<img width="809" alt="screen shot 2559-09-18 at 12 11 40 pm" src="https://cloud.githubusercontent.com/assets/747341/18613017/3ab6a84e-7d99-11e6-95c6-63e472cb0871.png">
<img width="1307" alt="screen shot 2559-09-18 at 12 11 02 pm" src="https://cloud.githubusercontent.com/assets/747341/18613018/4254a088-7d99-11e6-85a9-cad3e86f32cc.png">

**Comment by jordan8037310** [comment]
#8, #9, #10 are all available PRs that need to be tested.

**Comment by jordan8037310** [comment]
#34 is the appropriate fix for testing.

**Comment by RCheesley** [comment]
Please post at https://www.drupal.org/project/mautic if this is still an issue.
