### ISSUE TITLE
Use https for including tracking image and javascript

### ISSUE THREAD

**Issue by ronald070** [mautic/mautic-drupal#24]
Hi,

I dont know for sure if this is an issue.....

The module is including:
`<img` src="http://yourmautic.com/mtracking.gif" />
and 
`<script` src="http://yourmautic.com/media/js/mautic-form.js"></script>

Is there a way to use https for these includes?

Kind regards,
    Ronald

**Comment by escopecz** [comment]
Isn't it user who sets the Mautic URL with http or https in the plugin configuration?

**Comment by ronald070** [comment]
Oeps, your right. I did not think of that. 

I just change the URL in the settingsform of Mautic, and is working. It it use the Mautic URL.

Thanks.
