### ISSUE TITLE
Drupal.org Mautic Project

### ISSUE THREAD

**Issue by jordan8037310** [mautic/mautic-drupal#29]
At some point we should discuss getting updates merged over to https://www.drupal.org/sandbox/mautic/2453263.

Happy to be a contributor there and help manage the issue queue.

**Comment by escopecz** [comment]
Good idea! You've been added as a maintainer there.

**Comment by jordan8037310** [comment]
Great! I will close this and will cut a release for the project to drupal.org once we get recent pull requests merged in.
