### ISSUE TITLE
Include Mautic API library as dependency for 8.x-1.x branch

### ISSUE THREAD

**Issue by pietervanleuven** [mautic/mautic-drupal#37]
In order to support further functionality provided by the Mautic API, the Mautic API library should be added as a dependency to the module and an admin configuration form should be set-up to allow configuration of this API client.

I am currently also developing a mautic_reports submodule for the mautic 8.x module. This will provide some basic reporting through this API library: list Mautic fields, forms, contacts.

**Comment by RCheesley** [comment]
Please post any requests over at https://www.drupal.org/project/mautic
