### ISSUE TITLE
drop down for 6 7 8 - when 8 is selected it shows docs for 7 

### ISSUE THREAD

**Issue by cperg** [mautic/mautic-drupal#38]
Just a minor issue but could be very confusing to some. Also this is mautic-drupal - the word joomla in the discussion about the mautic image should be replaced...

**Comment by cperg** [comment]
Now I understand why the documentation is not up to the actual Drupal Version. Just attempted the installation and noticed you just have the old 7.x version here. It hasn't been updated to yml file requirements. I will see what can be done to help out.

**Comment by jordan8037310** [comment]
Please see #25 and #19 as they are in need of testing / community feedback.

**Comment by RCheesley** [comment]
Closing this issue as the project is now on drupal.org at https://www.drupal.org/project/mautic
