### ISSUE TITLE
TRACKING CODE POINTING TO LOCALHOST

### ISSUE THREAD

**Issue by nikoameer** [mautic/mautic-drupal#42]
Hello,

I just started working with mautic so I dont understand the problem I am facing. 
For some reason in my browser console I get net::ERR_CONNECTION_REFUSED. 
The error below:
OPTIONS http://localhost/mtc/event net::ERR_CONNECTION_REFUSED

also, mtracking.gif is pointing towards same address. 

The address points towards localhost ip instead of url that I have set in Drupal mautic configuration.

Can anyone help me what am I doing wrong or what I should do to make it work?

Thanks.

**Comment by jordan8037310** [comment]
Can you paste a copy of your configuration screen here?

**Comment by RCheesley** [comment]
If this is still an issue, please post over at https://www.drupal.org/project/mautic
