### ISSUE TITLE
Move to Drupal.org

### ISSUE THREAD

**Issue by cweagans** [mautic/mautic-drupal#7]
Hi there!

I suggest moving this module to Drupal.org. Note that you do need to go through an application process to do this, but I'm happy to help facilitate that process if you want to do it. I have administrative powers on Drupal.org, so when it's ready, I can approve the app.

A few things that I noticed while going through the repo:
- Your branches should be 6.x-1.x, 7.x-1.x, and 8.x-1.x to play nicely with the Drupal.org packaging and update systems
- Your current 6.x branch seems to have multiple modules in it for some reason
- You should define your own permission for configuring Mautic (rather than just using "access administration pages" - that permission does just what it says. It's sort of a kill switch for whether or not a user has access to /admin/*. In other words, your user would be required to have both "access administration pages" and "configure mautic")
- The D6 version should relocate it's admin page to /admin/settings/mautic (the URL was different back then. For D7 and D8, it should be /admin/config/mautic)
- You don't need this line: https://github.com/mautic/mautic-drupal/blob/7.x/mautic.info#L6  Drupal will automatically include your .module file. files[] is for specifying any _additional_ files that have classes in them (D7 has it's own autoloader - it'll scan everything in files[] to try to find classes and then build a registry of where to find what classes)

Generally, if you'd like some help with architecture on this module to make sure it'll play nicely with common caching mechanisms and the like, I'd be happy to help. If you want, I can even be the maintainer of the module on Drupal.org so that you don't have to go through the application process (you'd still have commit access, of course).

**Comment by dbhurley** [comment]
This is awesome! I was under the impression we were already listed on Drupal.org but we can certainly make sure we go through a few more steps to do it right. Your help would be much appreciated!

**Comment by cweagans** [comment]
Ah, I see that you have a Sandbox project: https://www.drupal.org/sandbox/mautic/2453263

The project application process is basically a way to get a real project URL like https://www.drupal.org/project/mautic

Going through this process also means that you are more or less covered by the security team procedures in the event that somebody finds a security issue in the module, and when you publish a new version, people's Drupal sites get notified accordingly. However, we can bypass that as I already have full project permissions. I'll fix up the module over the next few days and let you have a look.

**Comment by dbhurley** [comment]
Yep, just went and saw that myself. Thanks for the help, we definitely want to be listed the right way. Thanks again for the assist!

**Comment by jmolivas** [comment]
:+1:

**Comment by dbhurley** [comment]
@cweagans - I know it's been crazy busy in Drupal-land with D8 reaching RC soon, have you had any chance to look into moving off of sandbox to a proper project? Are you still able to help us get where we should be?

**Comment by jmolivas** [comment]
I am writing a Drupal 8 implementation for this project, I am planning to send a PR.

**Comment by cweagans** [comment]
I haven't had a chance, unfortunately. I wouldn't feel comfortable pushing it directly to Drupal.org as it is without some cleanup. @jmolivas definitely knows the standards and such though, so if he beats me to it, consider it just as good :)

**Comment by dbhurley** [comment]
You all are the best! Thank you both :+1: I knew things have been hectic so didn't want to expect or push too much, but really awesome to see if we can get listed prior to Oct 7.  Thank you both!! 

@jmolivas - let me know if you have any questions. got some great ideas for more in the future which would be awesome to chat about when time allows!

**Comment by jmolivas** [comment]
@dbhurley: I am already at mautic slack channel, feel free to ping me.

**Comment by rteijeiro** [comment]
@jmolivas are you still working in the D8 version of the module? Is it there anything I can do to help? Ping me any time, I would like to get it done as soon as possible ;)

**Comment by jmolivas** [comment]
@rteijeiro I do have the working code some clean up need to be done ex: inject services. But I can send a PR with my current version.

**Comment by rteijeiro** [comment]
That could be great @jmolivas. Then I can continue from there and also help testing it ;)

**Comment by rteijeiro** [comment]
Hi, just found this PR and I wonder which one is the best option: https://github.com/mautic/mautic-drupal/pull/19

I really need to move this forward.

Any ideas?

**Comment by jordan8037310** [comment]
I will be picking this up later this month.

**Comment by rteijeiro** [comment]
Great! @jordan8037310 let me know if you need any help. I can provide some resources to speed this up ;)

**Comment by jordan8037310** [comment]
@rteijeiro if you're interested in testing Drupal 8.x version there are two open PRs I could use some help testing, #19 and #25.

FWIW, there are more features in 7.x branch and approach has been updated to use shortcode module to manage injecting the mautic scripts. The 8.x approaches will likely have to be updated to leverage that.

**Comment by rinasek** [comment]
@jordan8037310 @rteijeiro I'll try to test both PRs this or next week. I will let you know how things go.

**Comment by jordan8037310** [comment]
#23 has been merged for 7.x. In addition, I have opened PRs for #31, #32, #33 which add some key Mautic functionality and some new functionality. Could use some testing from any interested. Once I have a review for each I will merge in and cut a release to drupal.org.

**Comment by rinasek** [comment]
@rteijeiro @jordan8037310 I have tested both PRs for D8 version and posted comments on each of them.  [#19](https://github.com/mautic/mautic-drupal/pull/19) does not work and [#25](https://github.com/mautic/mautic-drupal/pull/25) works without issue.

**Comment by jordan8037310** [comment]
Some work to get this onto Drupal.org is being tracked in #36. Currently don't have access to Sandbox project but hope to get unblocked there and get this out the door.

**Comment by Grienauer** [comment]
Currently there is this moduele on g.d.o. https://www.drupal.org/project/mautic
Maybe team up with the current maintainer or close this issue because it is done?

**Comment by rteijeiro** [comment]
I don't think the module in drupal.org has the same code than this module. Now I am co-maintainer of the mautic module in drupal.org and I'll try to merge both modules into one. Contact me if you want to contribute to this as well.

**Comment by idevit** [comment]
The official (merged) module is up for Drupal 8 and security reviewed.  
https://www.drupal.org/project/mautic  

this issue can be closed
